spring.application.name=stocksphere
spring.datasource.url=jdbc:mysql://root:hRqTwvDdAkwUeHKvMnhAdnouGSCUrqnS@mysql.railway.internal:3306/railway

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
